---
title: "Open Data Web APIs"
author: "Yichuan (James) Li"
date: "2020/7/7"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# API Key Setup

```{r}
library(tidyverse)
```

Do this in console eeverytime when setting up new API password:

```{r}
## library(usethis)
## edit_r_environ()
```

```{r}
movie_key <- Sys.getenv("OMDB_API_KEY")
```

```{r}
library(keyring)
```

```{r}
key_set("OMDB_API_KEY_SECURE")
```

```{r}
library(httr)
```

```{r}
mout <- GET(url = "http://www.omdbapi.com/",
            query = list(t = "The Lighthouse",
                         plot = "short", 
                         r = "json", 
                         apikey = key_get("OMDB_API_KEY_SECURE")))
status_code(mout)
headers(mout)
content(mout, as = "text")
```

# Tidycensus

```{r}
library(tidycensus)
```

CENSUS_API_KEY Setup:

```{r}
movie_key_2 <- Sys.getenv("CENSUS_API_KEY")
```

```{r}
key_set("OMDB_API_KEY_SECURE_2")
```

Exercise 1:

```{r}
m90 <- get_decennial(geography = "state", 
                     variables = "H043A001", 
                     year = 1990, 
                     key = key_get("OMDB_API_KEY_SECURE_2"))
head(m90)
nrow(m90)
```

```{r}
m90 %>% 
  ggplot(aes(x = value, y = reorder(NAME, value))) +
  geom_point()
```

Find A Variable:

```{r}
v17 <- load_variables(2017, "acs5", cache = TRUE)
```

Exercise 2:

```{r, error = TRUE}
c32000 <- load_variables(2000, "sf3", cache = TRUE)
c32000 %>% 
  filter(str_detect(concept, "Median Gross Rent")) # This code chunk won't run on my PC
```

```{r}
m2000 <- get_decennial(geography = "state", 
                       variables = "H063001",
                       year = 2000, 
                       key = key_get("OMDB_API_KEY_SECURE_2"))
head(m2000)
nrow(m2000)
```

```{r}
m90 %>% 
  mutate(year = 1990) -> m90
m2000 %>% 
  mutate(year = 2000) -> m2000

rbind.data.frame(m90, m2000) %>% 
  mutate(year = as_factor(year)) -> mgr
```

```{r}
mgr %>% 
  group_by(NAME) %>% 
  summarize(n = n()) %>% 
  filter(n !=2) -> unmatch

unmatch
```

```{r}
mgr %>% 
  filter(NAME != unmatch$NAME) -> mgr

mgr %>% 
  ggplot(aes(x = year, y = value)) +
  geom_boxplot()
```

```{r}
library(tidyr)
```

```{r, error = TRUE}
mgr %>% 
  select(-variable) %>% 
  pivot_wider(names_from = year, names_prefix = "y") -> mgr_wide  ##pivot_wider function not found

mgr_wide %>% 
  ggplot(aes(x = y1990, y = y2000)) +
  geom_point() +
  geom_smooth(se = FALSE, method = lm, color = "red", lty = 2)
```

```{r}
mgr_wide %>% 
  mutate(prent_change = (y2000 - y1990)/y1990, 
         rent_change = (y2000 - y1990)) %>% 
  arrange(desc(prent_change)) %>% 
  select(NAME, y1990, rent_change, prent_change) %>% 
  slice(1:5, 47:51)

lmout <- lm(y2000 ~ y1990, data = mgr_wide)
broom::tidy(lmout)
```

```{r}
library(jsonlite)
```

```{r}
json <- '["Mario", "Peach", null, "Bowser"]'
fromJSON(json)  ## could not find function "fromJSON"
str(fromJSON(json))
fromJSON(json, simplifyVector = FALSE)
```

```{r}
json <-
'[
  {"Name" : "Mario", "Age" : 32, "Occupation" : "Plumber"}, 
  {"Name" : "Peach", "Age" : 21, "Occupation" : "Princess"},
  {},
  {"Name" : "Bowser", "Occupation" : "Koopa"}
]'
mydf <- fromJSON(json)
mydf
```

```{r}
mydf$Ranking <- c(3, 1, 2, 4)
toJSON(mydf, pretty=TRUE)
```

```{r}
url_congress <- "https://theunitedstates.io/congress-legislators/legislators-current.json"

json_congress <- fromJSON(url_congress)
glimpse(json_congress)
```

```{r}
json_congress <- fromJSON(url_congress, flatten = TRUE)
glimpse(json_congress)
```

```{r}
library(lubridate)
json_congress %>% 
  mutate(bio.birthday = ymd(bio.birthday),
         bio.gender = as_factor(bio.gender),
         age = as.duration(interval(ymd(bio.birthday), today())/as.duration(years(1)))) -> json_congress

json_congress %>% 
  select(id.wikipedia, bio.birthday, bio.gender) %>% 
  arrange(bio.birthday) %>% 
  slice(c(1:3, (nrow(json_congress) -2):nrow(json_congress)))
```

```{r}
fct_count(json_congress$bio.gender)
```

```{r}
json_congress %>% 
  ggplot(aes(y = age, x = as.factor(bio.gender))) +
  geom_boxplot()
```

```{r}
json_congress %>% 
  ggplot(aes(x = age, color = as.factor(bio.gender))) +
  geom_density()
```

```{r}
json_congress %>% 
  ggplot(aes(y = age, x = as.factor(bio.gender))) +
  geom_jitter()
```

```{r}
tout <- t.test(age ~ bio.gender, data = json_congress)
tout
```

# Twitter APIs:
```{r, error = FALSE}
library(twitteR)
library(keyring)
setup_twitter_oauth(consumer_key = key_get("twitter_twitteR_API_key"),
 consumer_secret= key_get("twitter_twitteR_API_secret_key"),
  access_token = key_get("twitter_twitteR_access_token"),
  access_secret = key_get("twitter_twitteR_access_token_secret"))  ## Need APIs for all 
```

```{r, error = FALSE}
hadley <- getUser('hadleywickham')
str(hadley)
hadley$getFollowersCount()
hadley$getFriendes(n = 3)
hadley$getFavorites(n = 3)
```

```{r, error = FALSE}
R_tweets_all <- searchTwitter("#rstats + @handleywickham", n = 99)
one_tweet <- R_tweets_all[[1]]
one_tweet
str(one_tweet)
```

```{r, error = FALSE}
one_tweet$getCreated()
one_tweet$getScreenName()
one_tweet$getText()
df_all <- twlistToDF(R_tweets_all)

R_tweets <- strip_retweets(R_tweets_all)
df_no_rt <- twListToDF(R_tweets)
df_no_rt %>% 
  select(screenName, created, retweetCount, text) %>% 
  as_tibble() -> df_no_rt
```

```{r, error = FALSE}
R_tweets %>%
  map(function(x) x$getText()) %>%
  unlist() ->
  R_tweets_text
head(R_tweets_text, n = 3)
```

```{r, error = FALSE}
library(tidytext)
df_no_rt %>% 
  unnest_tokens(word, text) %>%
  anti_join(stop_words) ->
  df_tidy
df_tidy %>% 
  arrange(desc(retweetCount))
```

```{r, error = FALSE}
library(rtweet)

app_name <- "RRrtweet413"
token<- create_token(
  app = app_name,
  consumer_key = key_get("twitter_twitteR_API_key"),
  consumer_secret= key_get("twitter_twitteR_API_secret_key"),
  access_token = key_get("twitter_twitteR_access_token"),
  access_secret = key_get("twitter_twitteR_access_token_secret"))
```

```{r, error = FALSE}
get_friends("hadleywickham")
```

```{r, error = FALSE}
rt <- search_tweets(q = "#rstats AND 'data science'") # omit the retweets
rt <- search_tweets(q = "#rstats AND 'data science'", include_rts = FALSE)
head(rt$text, n = 2)
```

```{r}
rt <- search_tweets(q = "rstats AND 'data science'", include_rts = FALSE) %>%
  plain_tweets()
head(rt$text, n=3)
```

```{r, error = FALSE}
had <- get_timeline("hadleywickham", n = 3200) #3200 is max
ts_plot(had, "hours") # or "secs", "mins", "days", "weeks", "months", "years", 
```

```{r, error = FALSE}
lookup_users("DrIbram")
```

```{r, error = FALSE}
DrI <- get_timeline("DrIbram", n=200)
ts_plot(DrI, "days")
```

```{r}
library(tidyverse)
library(tigris)
library(sf)
library(viridis) 
options(tigris_use_cache = TRUE)
```

```{r}
baltimore <- get_acs(state = "MD", county = "Baltimore City", 
                     variables = "B19013_001",
                     geography = "tract",
                     geometry = TRUE, 
                     key = key_get("OMDB_API_KEY_SECURE_2"))
#head(baltimore)
```

```{r}
baltimore %>% 
ggplot(aes(fill = estimate)) + 
  geom_sf() + 
  coord_sf(crs = 26911) + 
  scale_fill_viridis_c(option = "magma") 
```

```{r}
racevars <- c(White = "P005003", 
              Black = "P005004", 
              Asian = "P005006", 
              Hispanic = "P004003")
baltimore_race <- get_decennial(state = "MD", county = "Baltimore City", 
                                geography = "tract", 
                                variables = racevars, geometry = TRUE, 
                                summary_var = "P001001",
                                key = key_get("CENSUS_API_KEY_SECURE"))
```

```{r}
baltimore_race %>%
  mutate(pct = 100 * (value / summary_value)) %>%
  ggplot(aes(fill = pct)) +
  facet_wrap(~variable) +
  geom_sf(color = NA) +
  coord_sf(crs = 26915) + 
  scale_fill_viridis_c()
```

```{r}
library(mapview)
mapview(baltimore, zcol = "estimate")
```

```{r}
dc_median_i_s <- get_acs(state = "DC",
                          county = "District of Columbia",
                          variables = c( "B01002_002","B01002_003",
                                         "B19013_001"),
                          geography = "tract", geometry = TRUE, 
                          key = Sys.getenv("CENSUS_API_KEY"))
dc_median_i_s %>% 
  mutate(CENSUS_TRACT = str_sub(GEOID,6,11)) ->
  dc_median
```

```{r}
dc_median %>% 
ggplot(aes(fill = estimate)) +
    geom_sf(aes(geometry = geometry),color = NA) +
    coord_sf(crs = 26915) + 
    scale_fill_viridis_c() 
```

```{r, error = FALSE}
crime <- read_csv("./data/dc-crimes-search-results.csv", 
                  col_types = cols(DISTRICT = col_factor(),
                                   WARD = col_factor(),
                                   PSA = col_factor(),
                                   METHOD= col_factor()
                                   ))
```

